# Generated by Django 4.2 on 2023-05-03 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NeasAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monumento_pi',
            name='valoraciones',
        ),
        migrations.RemoveField(
            model_name='valoracion_usuario',
            name='rutas',
        ),
        migrations.AddField(
            model_name='valoracion_usuario',
            name='monumento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeasAPP.monumento_pi'),
        ),
        migrations.AddField(
            model_name='valoracion_usuario',
            name='ruta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeasAPP.ruta'),
        ),
    ]
