# Generated by Django 4.2 on 2023-04-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NeasAPP', '0002_operador_tur_usuario_login_usuario_usuario_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='operador_tur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeasAPP.operador_tur'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='tematica',
            field=models.CharField(choices=[('Gastronómico', 'Gastronomico'), ('Cultural', 'Cultural'), ('Historico', 'Historico'), ('Ocio', 'Ocio'), ('Naturaleza', 'Naturaleza'), ('Religioso', 'Religioso')], max_length=100),
        ),
    ]
