# Generated by Django 4.2 on 2023-04-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeasAPP', '0003_alter_ruta_operador_tur_alter_ruta_tematica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(choices=[('Sevilla', 'Sevilla'), ('Cádiz', 'Cadiz'), ('Granada', 'Granada'), ('Cordoba', 'Cordoba'), ('Huelva', 'Huelva'), ('Jaen', 'Jaen'), ('Almeria', 'Almeria'), ('Malaga', 'Malaga'), ('Caceres', 'Caceres'), ('Badajoz', 'Badajoz'), ('Murcia', 'Murcia'), ('Alicante', 'Alicante'), ('Valencia', 'Valencia'), ('Castellon', 'Castellon'), ('Islas Baleares', 'Islas Baleares'), ('Tenerife', 'Tenerife'), ('Las Palmas', 'Las Palmas'), ('Albacete', 'Albacete'), ('Cuenca', 'Cuenca'), ('Toledo', 'Toledo'), ('Ciudad Real', 'Ciudad Real'), ('Guadalajara', 'Guadalajara'), ('Madrid', 'Madrid'), ('Teruel', 'Teruel'), ('Zaragoza', 'Zaragoza'), ('Huesca', 'Huesca'), ('Tarragona', 'Tarragona'), ('Lerida', 'Lerida'), ('Barcelona', 'Barcelona'), ('Gerona', 'Gerona'), ('La Rioja', 'La Rioja'), ('Navarra', 'Navarra'), ('Vizcaya', 'Vizcaya'), ('Alava', 'Alava'), ('Cantabria', 'Cantabria'), ('Asturias', 'Asturias'), ('Lugo', 'Lugo'), ('Orense', 'Orense'), ('Pontevedra', 'Pontevedra'), ('La Coruña', 'La Coruña'), ('León', 'Leon'), ('Palencia', 'Palencia'), ('Burgos', 'Burgos'), ('Soria', 'Soria'), ('Valladolid', 'Valladolid'), ('Segovia', 'Segovia'), ('Avila', 'Avila'), ('Salamanca', 'Salamanca'), ('Zamora', 'Zamora')], max_length=100),
        ),
    ]
